name: CI
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Message
         run: echo ${{ github.action_path }}
        
#   notification:
#     runs-on: ubuntu-latest
#     needs: 'build'
#     steps:
#       - name: Message
#         run: echo URL - https://translate.google.com
