name: CI
on: workflow_dispatch

env:
  PERSON: "Den"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        name: Run hello
        run: echo 'Hi from step1!'
        
      - id: step2
        name: Message
        run: echo "${{ env.PERSON }}" 
        
  notification:
    runs-on: ubuntu-latest
    needs: 'build'
    steps:
      - name: Message
        run: echo URL - https://translate.google.com/
