name: CI
on: workflow_dispatch

env:
  PERSON: "Den"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello
        run: echo Hello, ${{ env.PERSON }}!
        id: test
      - name: Message
        run: echo Hello, ${{ steps.jobs.outputs.html_url }}
        
  notification:
    runs-on: ubuntu-latest
    needs: 'build'
    steps:
      - name: Message
        run: echo Hello, ${{ steps.jobs.outputs.html_url }}
