name: deployment

# Workflow triggered manually
on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'Put version tag'
        required: true
        type: string
      tier:
        description: 'Choose deployment env'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod

jobs:
  attention-notification:
    if: ${{ always() }}
    uses: dsmyk10/action-test-repo/.github/workflows/notification.yml@main
    with:
      deploy-result: ${{ needs.deploy.result }}
      workflow-name: ${{ github.workflow }}
      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-step
        run: echo work process!!!!!   
      

  result-notification:
    if: ${{ always() }}
    needs: deploy
    uses: dsmyk10/action-test-repo/.github/workflows/notification.yml@main
    with:
      deploy-result: ${{ needs.deploy.result }}
      workflow-name: ${{ github.workflow }}
