name: deployment

# Workflow triggered manually
on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'Put version tag'
        required: true
        type: string
      env:
        description: 'Choose deployment env'
        required: true
        default: 'All(env-1, env-2, env-3)'
        type: choice
        options:
          - All(env-1, env-2, env-3)
          - env-1
          - env-2
          - env-3

jobs:
  started-notification:
    if: ${{ always() }}
    uses: dsmyk10/action-test-repo/.github/workflows/notification.yml@main
    with:
      workflow-name: ${{ github.workflow }}
      notification-type: "started"
        
  env-1-deploy:
    needs: started-notification
    if: inputs.env == 'All(env-1, env-2, env-3)' || inputs.env == 'env-1'
    runs-on: ubuntu-latest
    steps:
      - name: deploy-env-1
        run: echo work proccess !!! 
        
  env-2-deploy:
    needs: started-notification
    if: inputs.env == 'All(env-1, env-2, env-3)' || inputs.env == 'env-2'
    runs-on: ubuntu-latest
    steps:
      - name: deploy-env-2
        run: echo work proccess !!! 
        
  env-3-deploy:
    needs: started-notification
    if: inputs.env == 'All(env-1, env-2, env-3)' || inputs.env == 'env-3'
    runs-on: ubuntu-latest
    steps:
      - name: deploy-env-3
        run: echo work proccess !!!      

  result-notification:
    if: ${{ always() }}
    needs: [env-1-deploy, env-2-deploy, env-3-deploy]
    uses: dsmyk10/action-test-repo/.github/workflows/notification.yml@main
    with:
      env-1-deploy-result: ${{ needs.env-1-deploy.result }}
      env-2-deploy-result: ${{ needs.env-2-deploy.result }}
      env-3-deploy-result: ${{ needs.env-3-deploy.result }}
      workflow-name: ${{ github.workflow }}
