name: notification

on:
  workflow_call:
    inputs:
      env-1-deploy-result:
        type: string
      env-2-deploy-result: 
        type: string
      env-3-deploy-result: 
        type: string
      workflow-name:
        type: string
      notification-type:
        type: string

jobs:
  started-notification:
    runs-on: ubuntu-latest
    steps:
      - name: "MESSAGE"
        if: inputs.notification-type == 'started'
        run: echo "Deploment starts!!!"
        
  result-notification:
    runs-on: ubuntu-latest
    steps:
      - name: 'Success notification'
#         if: inputs.matrix-deploy-result == 'success' || inputs.region-deploy-result == 'success'
        run: |
          echo env-1-notification ${{ inputs.env-1-deploy-result }}
          echo env-2-notification ${{ inputs.env-2-deploy-result }}
          echo env-3-notification ${{ inputs.env-3-deploy-result }}
        
        
#       - name: 'Failure notification'
#         if: inputs.matrix-deploy-result == 'failure' || inputs.region-deploy-result == 'failure'
#         run: echo Failure ${{ inputs.workflow-name }}  
        
#       - name: 'Cancelled notification'
#         if: inputs.matrix-deploy-result == 'cancelled' || inputs.region-deploy-result == 'cancelled'
#         run: echo Cancelled ${{ inputs.workflow-name }}  
        
