name: notification

on:
  workflow_call:
    inputs:
      matrix-deploy-result:
        type: string
      region-deploy-result: 
        type: string
      workflow-name:
        type: string
      notification-type:
        type: string

jobs:
  started-notification:
    runs-on: ubuntu-latest
    steps:
      - name: "MESSAGE"
        if: inputs.notification-type == 'started'
        run: echo "Deploment starts!!!"
        
  result-notification:
    runs-on: ubuntu-latest
    steps:        
      - name: 'Success notification'
        if: inputs.matrix-deploy-result == 'success' || inputs.region-deploy-result == 'success'
        run: echo Success ${{ inputs.workflow-name }}  
        
      - name: 'Failure notification'
        if: inputs.matrix-deploy-result == 'failure' || inputs.region-deploy-result == 'failure'
        run: echo Failure ${{ inputs.workflow-name }}  
        
      - name: 'Cancelled notification'
        if: inputs.matrix-deploy-result == 'cancelled' || inputs.region-deploy-result == 'cancelled'
        run: echo Cancelled ${{ inputs.workflow-name }}  
        
