name: notification

on:
  workflow_call:
    inputs:
      deploy-result:
        type: string
      workflow-name:
        type: string
      notification-type:
        type: string

jobs:
  resoult-notification:
    runs-on: ubuntu-latest
    steps:
      - name: "Attention"
        if: inputs.notification-type == 'attention'
        run: echo "Deploment starts!!!"
        
      - name: 'Success notification'
        if: inputs.deploy-result == 'success'
        run: echo Success ${{ inputs.workflow-name }}  
        
      - name: 'Failure notification'
        if: inputs.deploy-result == 'failure'
        run: echo Failure ${{ inputs.workflow-name }}  
        
      - name: 'Cancelled notification'
        if: inputs.deploy-result == 'cancelled'
        run: echo Cancelled ${{ inputs.workflow-name }}  
        
